### ISSUE TITLE
INFOGRAFIA 

### ISSUE THREAD

**Issue by Anamichel-leon** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Anamichel-leon#1]
[INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Anamichel-leon/files/15204658/INFOGRAFIA.pdf)

**Comment by carlos0716c** [comment]
CALIFICADO DE ACUERDO A LA RÚBRICA

Partes de la infografía: 4
Coherencia y pertinencia: 4
Organización de la información: 4
Diseño y composición de la infografía: 4
Creatividad: 4
Total=20
CALIFICACIÓN=20/20

**Comment by josealfredo79** [comment]
bien hecho y revisado..
